### ISSUE TITLE
Can't reopen Main View after closing it

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclist2#120]
The following actions:
* open Main View
* work in Main View
* close Main View (using [X] at right end of title bar)
* try to open Main View

results in the following errors:
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Children: duplicate children added: parent = Grid hgap=4.0, vgap=4.0, alignment=TOP_LEFT
	at javafx.scene.Parent$2.onProposedChange(Parent.java:451)
	at com.sun.javafx.collections.VetoableListDecorator.add(VetoableListDecorator.java:206)
	at javafx.scene.layout.GridPane.add(GridPane.java:965)
	at edu.utexas.cycic.Cycic.details(Unknown Source)
	at edu.utexas.cycic.Cycic.init(Unknown Source)
	at edu.utexas.cycic.Cycic.<init>(Unknown Source)
	at edu.utexas.cycic.tools.CycicTool.getView(Unknown Source)
	at edu.utah.sci.cyclist.core.presenter.VisWorkspacePresenter.addTool(Unknown Source)
	at edu.utah.sci.cyclist.core.presenter.VisWorkspacePresenter.access$000(Unknown Source)
	at edu.utah.sci.cyclist.core.presenter.VisWorkspacePresenter$2.call(Unknown Source)
	at edu.utah.sci.cyclist.core.presenter.VisWorkspacePresenter$2.call(Unknown Source)
	at edu.utah.sci.cyclist.core.ui.views.VisWorkspace.lambda$build$8(Unknown Source)
	at edu.utah.sci.cyclist.core.ui.views.VisWorkspace$$Lambda$179/154130202.handle(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$DnDGesture.fireEvent(Scene.java:2934)
	at javafx.scene.Scene$DnDGesture.processTargetDrop(Scene.java:3160)
	at javafx.scene.Scene$DnDGesture.access$6400(Scene.java:2910)
	at javafx.scene.Scene$DropTargetListener.drop(Scene.java:2874)
	at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$306(GlassSceneDnDEventHandler.java:81)
	at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler$$Lambda$330/1417674141.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(GlassSceneDnDEventHandler.java:79)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$359(GlassViewEventHandler.java:663)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$$Lambda$329/1946023201.get(Unknown Source)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:404)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(GlassViewEventHandler.java:662)
	at com.sun.glass.ui.View.handleDragDrop(View.java:712)
	at com.sun.glass.ui.View.notifyDragDrop(View.java:1027)
	at com.sun.glass.ui.gtk.GtkDnDClipboard.pushToSystemImpl(Native Method)
	at com.sun.glass.ui.gtk.GtkDnDClipboard.pushToSystem(GtkDnDClipboard.java:39)
	at com.sun.glass.ui.SystemClipboard.flush(SystemClipboard.java:51)
	at com.sun.glass.ui.ClipboardAssistance.flush(ClipboardAssistance.java:59)
	at com.sun.javafx.tk.quantum.QuantumClipboard.flush(QuantumClipboard.java:274)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startDrag(QuantumToolkit.java:1226)
	at javafx.scene.Scene$DnDGesture.dragDetectedProcessed(Scene.java:2954)
	at javafx.scene.Scene$DnDGesture.process(Scene.java:3023)
	at javafx.scene.Scene$DnDGesture.access$8200(Scene.java:2910)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3774)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3486)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2495)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:350)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$350(GlassViewEventHandler.java:385)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$$Lambda$290/422906876.get(Unknown Source)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:404)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:384)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:927)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at com.sun.glass.ui.gtk.GtkApplication$$Lambda$41/1364335809.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by gonuke** [comment]
Resolved by making Main View unclosable
