### ISSUE TITLE
release branch fails to run

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclist2#80]
I get
```
$ java -jar deploy/dist/cyclist.jar 
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$152(LauncherImpl.java:182)
	at com.sun.javafx.application.LauncherImpl$$Lambda$55/1688376486.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at edu.utah.sci.cyclist.core.controller.CyclistController.setScreen(Unknown Source)
	at edu.utah.sci.cyclist.Cyclist.start(Unknown Source)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$159(LauncherImpl.java:863)
	at com.sun.javafx.application.LauncherImpl$$Lambda$58/60630079.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$172(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl$$Lambda$50/1766822961.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$53/1651623707.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$51/1496724653.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at com.sun.glass.ui.gtk.GtkApplication$$Lambda$41/1364335809.run(Unknown Source)
	... 1 more
Exception running application edu.utah.sci.cyclist.Cyclist
```

any ides @FlanFlanagan, @yarden-livnat, @gonuke?

**Comment by gonuke** [comment]
It works for me.  I do get some errors at startup, but it works fine.

**Comment by gidden** [comment]
it now builds for me, someone likely checked in a fix

On Thu, Jun 4, 2015 at 1:58 PM, Paul Wilson <notifications@github.com>
wrote:

> It works for me. I do get some errors at startup, but it works fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/80#issuecomment-109009872>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gidden** [comment]
and I lied, it still fails. sorry all!

**Comment by gidden** [comment]
the term "build" here is wrong. it fails to run

**Comment by yarden-livnat** [comment]
I see the problem. At one point the list of Cycic tools factories were separated from the main list (Radio?). Unfortunately this breaks the restore capabilities of Cyclist.
I’ll find a solution soon.

**Comment by yarden-livnat** [comment]
I see the problem. At one point the list of Cycic tools factories were separated from the main list (Radio?). Unfortunately this breaks the restore capabilities of Cyclist.
I’m working on a solution.

**Comment by FlanFlanagan** [comment]
Umm...weird. I didn't move them.

**Comment by yarden-livnat** [comment]
Fixed.
However, now Cycic tools are automatically saved and restored on exit/start and this seems to cause a problem

5371 [JavaFX Application Thread] INFO  edu.utexas.cycic.DataArrays  - Adding archetype :cycaless:DeployInst
java.lang.NullPointerException
8373 [JavaFX Application Thread] INFO  edu.utexas.cycic.DataArrays  - Adding archetype :cycamore:DeployInst
	at edu.utexas.cycic.XMLReader.readSchema_new(XMLReader.java:143)
	at edu.utexas.cycic.DataArrays.retrieveSchema(DataArrays.java:141)
	at edu.utexas.cycic.DataArrays.defaultJsonReader(DataArrays.java:168)

**Comment by yarden-livnat** [comment]
@FlanFlanagan 
XMLReader.readSchema_new
calls on line 143					
   for(int j = 0; j < node.item(i).getAttributes().getLength(); j++){

but getAttributes() returns null. Is it a legal value? If so than we should check for it. Otherwise it might be a problem somewhere else.

**Comment by FlanFlanagan** [comment]
I think the problem is the Cycaless:DeployInst. It won't load because it's out dated. Just needs to be removed from the metadata file.

**Comment by gidden** [comment]
the cycaless facilities probably dont need to be in there anymore..

On Thu, Jun 4, 2015 at 4:16 PM, FlanFlanagan <notifications@github.com>
wrote:

> I think the problem is the Cycaless:DeployInst. It won't load because it's
> out dated. Just needs to be removed from the metadata file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/80#issuecomment-109054534>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192
